openapi: 3.0.0
info:
  title: Edge Impulse Admin API
  version: 1.0.0
servers:
- url: https://studio.edgeimpulse.com/v1
security:
- ApiKeyAuthentication: []
- JWTAuthentication: []
- JWTHttpHeaderAuthentication: []
tags:
- name: Admin
paths:
  /api/admin/metrics:
    get:
      summary: Get global metrics
      description: Admin-only API to get global metrics.
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:read
      tags:
      - Admin
      operationId: adminGetMetrics
  /api/admin/metrics/reports:
    get:
      summary: Get global metrics reports
      description: Admin-only API to get global metrics reports.
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:read
      tags:
      - Admin
      operationId: adminGetMetricsReports
    post:
      summary: Create a new global metrics report
      description: 'Admin-only API to create a new global metrics report.

        A job is created to process the report request and the job details are returned in the response.

        '
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:read
      tags:
      - Admin
      operationId: adminCreateMetricsReport
  /api/admin/metrics/reports/{reportId}:
    get:
      summary: Get global metrics report
      description: Admin-only API to get a global metrics report.
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:read
      tags:
      - Admin
      operationId: adminGetMetricsReport
    delete:
      summary: Delete global metrics report
      description: Admin-only API to delete a global metrics report.
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:write
      tags:
      - Admin
      operationId: adminDeleteMetricsReport
  /api/admin/metrics/reports/{reportId}/download:
    get:
      summary: Download global metrics report
      description: Admin-only API to download a global metrics report.
      x-internal-api: true
      security:
      - permissions:
        - admin:metrics:read
      tags:
      - Admin
      operationId: adminDownloadMetricsReport
  /api/admin/infra/migrations:
    get:
      summary: Get data migrations
      description: Admin-only API to get data migrations.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:migrations:read
      tags:
      - Admin
      operationId: adminGetDataMigrations
  /api/admin/infra/migrations/{migrationId}:
    get:
      summary: Get data migration
      description: Admin-only API to get a data migration.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:migrations:read
      tags:
      - Admin
      operationId: adminGetDataMigration
    post:
      summary: Run or pause a data migration
      description: Admin-only API to run or pause a data migration.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:migrations:write
      tags:
      - Admin
      operationId: adminToggleDataMigration
  /api/admin/infra/disallowedEmailDomains:
    get:
      summary: Get the list of disallowed email domains
      description: Admin-only API to get the list of disallowed email domains.
      x-internal-api: true
      tags:
      - Admin
      operationId: adminGetDisallowedEmailDomains
    put:
      summary: Add a disallowed email domain
      description: Admin-only API to add an email domain to the list of disallowed email domains.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:disallowedEmailDomains:write
      tags:
      - Admin
      operationId: adminAddDisallowedEmailDomain
  /api/admin/infra/disallowedEmailDomains/{domainName}:
    delete:
      summary: Delete disallowed email domain
      description: Admin-only API to delete an email domain from the list of disallowed email domains.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:disallowedEmailDomains:write
      tags:
      - Admin
      operationId: adminDeleteDisallowedEmailDomain
  /api/admin/infra/featureFlags:
    get:
      summary: Get all feature flags
      description: Admin-only API to get all feature flags.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:featureFlags:read
      tags:
      - Admin
      operationId: adminGetFeatureFlags
  /api/admin/infra/featureFlags/{featureId}:
    put:
      summary: Set a feature flag ON
      description: Admin-only API to set a feature flag ON. Setting a feature flag ON essentially enables the feature for all users.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:featureFlags:write
      tags:
      - Admin
      operationId: adminEnableFeature
    delete:
      summary: Set a feature flag OFF
      description: Admin-only API to delete a feature flag. Deleting a feature flag essentially disables the feature for all users.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:featureFlags:write
      tags:
      - Admin
      operationId: adminDisableFeature
  /api/admin/infra/config:
    get:
      summary: Get all studio config
      description: Admin-only API to get all studio config.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:config:read
      tags:
      - Admin
      operationId: adminGetStudioConfig
  /api/admin/infra/config/{configKey}:
    post:
      summary: Update studio config
      description: Admin-only API to update a studio config item.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:config:write
      tags:
      - Admin
      operationId: adminSetStudioConfig
    delete:
      summary: Delete a studio config item
      description: Admin-only API to delete a studio config item.
      x-internal-api: true
      security:
      - permissions:
        - admin:infra:config:write
      tags:
      - Admin
      operationId: adminDeleteStudioConfig
  /api/admin/users:
    get:
      summary: Get all users
      description: Admin-only API to get the list of all registered users.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetUsers
  /api/admin/users/{userId}:
    get:
      summary: Get user
      description: Admin-only API to get information about a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetUser
    post:
      summary: Update user
      description: Admin-only API to update user properties.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:write
      tags:
      - Admin
      operationId: adminUpdateUser
    delete:
      summary: Delete a user
      description: Admin-only API to delete a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:write
      tags:
      - Admin
      operationId: adminDeleteUser
  /api/admin/users/{userId}/metrics:
    get:
      summary: Get user metrics
      description: Admin-only API to get marketing metrics about a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetUserMetrics
  /api/admin/users/{userId}/permissions:
    post:
      summary: Update user permissions
      description: Admin-only API to update the list of permissions for a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:permissions:write
      tags:
      - Admin
      operationId: adminUpdateUserPermissions
  /api/admin/users/{userId}/jobs:
    get:
      summary: Get user jobs
      description: Admin-only API to get the list of all project jobs for a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetUserJobs
  /api/admin/trials:
    post:
      summary: Create user enterprise trial
      description: Admin-only API to create an enterprise trial for a user.
      x-internal-api: true
      security:
      - permissions:
        - admin:trials:write
      tags:
      - Admin
      operationId: adminCreateTrial
  /api/admin/trials/{enterpriseTrialId}:
    get:
      summary: Get enterprise trial
      description: Admin-only API to get a specific enterprise trial.
      x-internal-api: true
      security:
      - permissions:
        - admin:trials:read
      tags:
      - Admin
      operationId: adminGetTrial
    put:
      summary: Update enterprise trial
      description: Admin-only API to update an enterprise trial.
      x-internal-api: true
      security:
      - permissions:
        - admin:trials:write
      tags:
      - Admin
      operationId: adminUpdateTrial
    delete:
      summary: Delete enterprise trial
      description: Admin-only API to delete an enterprise trial.
      x-internal-api: true
      security:
      - permissions:
        - admin:trials:write
      tags:
      - Admin
      operationId: adminDeleteTrial
  /api/admin/trials/{enterpriseTrialId}/upgrade:
    post:
      summary: Upgrade enterprise trial to a full enterprise account
      description: Admin-only API to upgrade a specific enterprise trial to a full enterprise account.
      x-internal-api: true
      security:
      - permissions:
        - admin:trials:write
      tags:
      - Admin
      operationId: adminUpgradeTrial
  /api/admin/projects:
    get:
      summary: Get all projects
      description: Admin-only API to get the list of all projects.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:read
      tags:
      - Admin
      operationId: adminGetProjects
    post:
      summary: Create a new project
      description: Admin-only API to create a new free tier project.
      x-internal-api: true
      tags:
      - Admin
      security:
      - permissions:
        - admin:projects:write
      operationId: adminCreateProject
  /api/admin/projects/{projectId}:
    get:
      summary: Get project
      description: Admin-only API to get project information.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:read
      tags:
      - Admin
      operationId: adminGetProject
    post:
      summary: Update project
      description: Admin-only API to update project properties.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:write
      tags:
      - Admin
      operationId: adminUpdateProject
    delete:
      summary: Delete a project
      description: Admin-only API to delete a project.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:write
      tags:
      - Admin
      operationId: adminDeleteProject
  /api/admin/projects/{projectId}/members:
    post:
      summary: Add user to a project
      description: Admin-only API to add a user to a project. If no user is provided, the current user is used.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:members:write
      tags:
      - Admin
      operationId: adminAddUserToProject
  /api/admin/projects/{projectId}/members/{userId}:
    delete:
      summary: Remove user from a project
      description: Admin-only API to remove a user from a project.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:members:write
      tags:
      - Admin
      operationId: adminRemoveUserFromProject
  /api/admin/projects/{projectId}/jobs:
    get:
      summary: Get project jobs
      description: Admin-only API to get the list of all jobs for a project.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:read
      tags:
      - Admin
      operationId: adminGetProjectJobs
  /api/admin/organizations:
    get:
      summary: Get all organizations
      description: Admin-only API to get the list of all organizations.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizations
    post:
      summary: Create a new organization
      description: Admin-only API to create a new organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminCreateOrganization
  /api/admin/organizations/{organizationId}:
    get:
      summary: Organization information
      description: Admin-only API to list all information about this organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationInfo
    post:
      summary: Update organization
      description: Admin-only API to update organization properties such as name and logo.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminUpdateOrganization
    delete:
      summary: Delete an organization
      description: Admin-only API to delete an organization. If `fullDeletion` is set, it deletes the organization's identifiable information and files. Otherwise, it soft deletes the organization by setting its `delete_date` value.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminDeleteOrganization
  /api/admin/organizations/{organizationId}/restore:
    post:
      summary: Restore an organization
      description: 'Admin-only API to restore a soft deleted organization. All organization projects sharing the same deletion date as that of the organization will also be restored. If this is a trial organization that was never upgraded to a paid plan then the organization will be restored to its original trial state.

        '
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminRestoreOrganization
  /api/admin/organizations/{organizationId}/usage/computeTime:
    get:
      summary: Get organization compute time usage
      description: Admin-only API to get compute time usage for an organization over a period of time.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationComputeTimeUsage
  /api/admin/organizations/{organizationId}/usage/reports:
    get:
      summary: Get all usage reports
      description: Admin-only API to get all usage reports for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationUsageReports
    post:
      summary: Creates a new usage report
      description: Admin-only API to create a new usage report for an organization. A job is created to process the report request and the job details are returned in the response.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminCreateOrganizationUsageReport
  /api/admin/organizations/{organizationId}/usage/reports/{reportId}:
    get:
      summary: Get usage report
      description: Admin-only API to get a usage report for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationUsageReport
    delete:
      summary: Delete usage report
      description: Admin-only API to delete a usage report for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminDeleteOrganizationUsageReport
  /api/admin/organizations/{organizationId}/usage/reports/{reportId}/download:
    get:
      summary: Download usage report
      description: Admin-only API to download a usage report for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminDownloadOrganizationUsageReport
  /api/admin/organizations/{organizationId}/members:
    post:
      summary: Add user to an organization
      description: Admin-only API to add a user to an organization. If no user is provided, the current user is used.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:members:write
      tags:
      - Admin
      operationId: adminAddUserToOrganization
  /api/admin/organizations/{organizationId}/members/{userId}:
    delete:
      summary: Remove user from an organization
      description: Admin-only API to remove a user from an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:members:write
      tags:
      - Admin
      operationId: adminRemoveUserFromOrganization
  /api/admin/organizations/{organizationId}/projects:
    post:
      summary: Create a new organization project
      description: Admin-only API to create a new project for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:write
      tags:
      - Admin
      operationId: adminCreateOrganizationProject
  /api/admin/organizations/{organizationId}/exports:
    get:
      summary: Get all organization data exports
      description: Admin-only API to get the list of all data exports for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationDataExports
    post:
      summary: Create a new organization data export
      description: 'Admin-only API to create a new data export for an organization.

        A job is created to process the export request and the job details are returned in the response.

        '
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminCreateOrganizationDataExport
  /api/admin/organizations/{organizationId}/exports/{exportId}:
    get:
      summary: Get organization data export
      description: Admin-only API to get a data export for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationDataExport
    delete:
      summary: Delete organization data export
      description: Admin-only API to delete a data export for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminDeleteOrganizationDataExport
    put:
      summary: Update organization data export
      description: Admin-only API to update a data export for an organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:write
      tags:
      - Admin
      operationId: adminUpdateOrganizationDataExport
  /api/admin/organizations/{organizationId}/jobs:
    get:
      summary: Get organization jobs
      description: Admin-only API to get the list of all jobs for a organization.
      x-internal-api: true
      security:
      - permissions:
        - admin:organizations:read
      tags:
      - Admin
      operationId: adminGetOrganizationJobs
  /api/admin/sso:
    get:
      summary: Get SSO settings
      description: Admin-only API to get the SSO settings.
      x-internal-api: true
      tags:
      - Admin
      x-middleware:
      - RequiresSudo
      operationId: adminGetSSOSettings
  /api/admin/sso/{domainName}:
    get:
      summary: Get SSO settings for a domain
      description: Admin-only API to get the list of identity providers enabled for a given domain.
      x-internal-api: true
      tags:
      - Admin
      x-middleware:
      - RequiresSudo
      operationId: adminGetSSODomainIdPs
    put:
      summary: Add or update SSO settings for a domain
      description: Admin-only API to set the list of identity provider for a given domain.
      x-internal-api: true
      tags:
      - Admin
      x-middleware:
      - RequiresSudo
      operationId: adminAddOrUpdateSSODomainIdPs
    delete:
      summary: Delete SSO settings for a domain
      description: Admin-only API to delete the list of identity providers for a given domain.
      x-internal-api: true
      tags:
      - Admin
      x-middleware:
      - RequiresSudo
      operationId: adminDeleteSSODomainIdPs
  /api/admin/jobs/{jobId}/details:
    get:
      summary: Get job execution details
      description: Get the job execution details including inner jobs
      x-internal-api: true
      security:
      - permissions:
        - admin:jobs:read
      operationId: adminGetJobDetails
      tags:
      - Admin
  /api/admin/jobs/{jobId}/logs:
    get:
      summary: Get job logs
      description: Get the logs for a job.
      x-internal-api: true
      security:
      - permissions:
        - admin:jobs:read
      operationId: adminGetJobsLogs
      tags:
      - Admin
  /api/admin/jobs/{jobId}/metrics:
    get:
      summary: Get job usage metrics
      description: Get cpu/memory usage metrics, if the job is a Kubernetes job
      x-internal-api: true
      security:
      - permissions:
        - admin:jobs:read
      operationId: adminGetJobsMetrics
      tags:
      - Admin
  /api/admin/emails/{email}/verification-code:
    get:
      summary: Get enterprise trial email verification code
      description: Get the enterprise trial verification code of the specified email.
      x-internal-api: true
      security:
      - permissions:
        - admin:emails:verification:code:read
      operationId: adminGetEmailVerificationCode
      tags:
      - Admin
  /api/admin/find-user:
    get:
      summary: Find a user
      description: DEPRECATED. Admin-only API to find a user by username or email address.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminFindUser
      deprecated: true
  /api/admin/users-ids:
    get:
      summary: Get all user IDs
      description: DEPRECATED. Admin-only API to get list of all users.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetAllUserIds
      deprecated: true
  /api/admin/users-ids/active:
    get:
      summary: Get all user IDs (active last 30 days)
      description: DEPRECATED. Admin-only API to get list of all users that have been active in the past 30 days.
      x-internal-api: true
      security:
      - permissions:
        - admin:users:read
      tags:
      - Admin
      operationId: adminGetAllActiveUserIds
      deprecated: true
  /api/admin/projects/{projectId}/add:
    post:
      summary: Add current user to a project
      description: DEPRECATED. Admin-only API to add the current user to a project.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:members:write
      tags:
      - Admin
      operationId: adminAddUserToProjectDeprecated
      deprecated: true
  /api/admin/projects/{projectId}/remove:
    post:
      summary: Remove current user from a project
      description: DEPRECATED. Admin-only API to remove the current user from a project.
      x-internal-api: true
      security:
      - permissions:
        - admin:projects:members:write
      tags:
      - Admin
      operationId: adminRemoveUserFromProjectDeprecated
      deprecated: true
components:
  securitySchemes:
    ApiKeyAuthentication:
      type: apiKey
      in: header
      name: x-api-key
    JWTAuthentication:
      type: apiKey
      in: cookie
      name: jwt
    JWTHttpHeaderAuthentication:
      type: apiKey
      in: header
      name: x-jwt-token
